serverAddr = "43.130.11.12"
serverPort = 2053
auth.method = "token"
auth.token = "20190501sdgl"

log.to = "./frpc.log"
log.level = "info"
log.maxDays = 7

[[proxies]]
name = "rdp"
type = "stcp"
secretKey = "20190501sdgl"
localIP = "127.0.0.1"
localPort = 443
