serverAddr = "43.135.118.188"
serverPort = 7000
auth.method = "token"
auth.token = "20190501sdgl"

[[proxies]]
name = "xray_43.135.118.188"
type = "tcp"
localIP = "127.0.0.1"
localPort = 443
remotePort = 5763